# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 533)
        MainWindow.setStyleSheet("#menu_widget {\n"
"    background-color:  #313a46;\n"
"}\n"
"#menu_widget QPushButton, QLabel{\n"
"    height: 50px;\n"
"    border: none;\n"
"}\n"
"#menu_widget QPushButton:hover{\n"
"    background-color: rgba(86,101,115,0.5);\n"
"}\n"
"#menu_widget QLabel{\n"
"    color: #fff;\n"
"}\n"
"#menu_widget QPushButton{\n"
"    color:  #737373;\n"
"}\n"
"#menu_widget QPushButton:hover{\n"
"    color:  #fff;\n"
"}\n"
"#MainWindow{\n"
"    background-color:#fff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.menu_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menu_widget.setObjectName("menu_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.menu_widget)
        self.logo.setMinimumSize(QtCore.QSize(35, 35))
        self.logo.setMaximumSize(QtCore.QSize(35, 35))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icons/icons/icons8-출석-표-64.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.title = QtWidgets.QLabel(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(16)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_button = QtWidgets.QPushButton(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.home_button.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-집-48 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon)
        self.home_button.setIconSize(QtCore.QSize(18, 18))
        self.home_button.setCheckable(True)
        self.home_button.setAutoExclusive(True)
        self.home_button.setObjectName("home_button")
        self.verticalLayout.addWidget(self.home_button)
        self.data_button = QtWidgets.QPushButton(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.data_button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-영상-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.data_button.setIcon(icon1)
        self.data_button.setIconSize(QtCore.QSize(18, 18))
        self.data_button.setCheckable(True)
        self.data_button.setAutoExclusive(True)
        self.data_button.setObjectName("data_button")
        self.verticalLayout.addWidget(self.data_button)
        self.learn_button = QtWidgets.QPushButton(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.learn_button.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-책-공개-시험-48 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.learn_button.setIcon(icon2)
        self.learn_button.setIconSize(QtCore.QSize(18, 18))
        self.learn_button.setCheckable(True)
        self.learn_button.setAutoExclusive(True)
        self.learn_button.setObjectName("learn_button")
        self.verticalLayout.addWidget(self.learn_button)
        self.detect_button = QtWidgets.QPushButton(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.detect_button.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-검사-48 (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detect_button.setIcon(icon3)
        self.detect_button.setIconSize(QtCore.QSize(18, 18))
        self.detect_button.setCheckable(True)
        self.detect_button.setAutoExclusive(True)
        self.detect_button.setObjectName("detect_button")
        self.verticalLayout.addWidget(self.detect_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 248, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.helper_button = QtWidgets.QPushButton(self.menu_widget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(13)
        self.helper_button.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-search-more-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helper_button.setIcon(icon4)
        self.helper_button.setIconSize(QtCore.QSize(18, 18))
        self.helper_button.setCheckable(True)
        self.helper_button.setAutoExclusive(True)
        self.helper_button.setObjectName("helper_button")
        self.verticalLayout_2.addWidget(self.helper_button)
        self.gridLayout.addWidget(self.menu_widget, 0, 0, 1, 1)
        self.content_widget = QtWidgets.QWidget(self.centralwidget)
        self.content_widget.setObjectName("content_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.content_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 458, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border: 4px solid#a6aaaf;\n"
"border-radius: 5px;\n"
"padding: 1px 5px;\n"
"background-color: #a6aaaf;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border: 4px solid#a6aaaf;\n"
"border-radius: 5px;\n"
"padding: 1px 5px;\n"
"background-color: #a6aaaf;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(20, 434, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: 2px solid#a6aaaf;\n"
"border-radius: 5px;\n"
"padding: 1px 5px;\n"
"\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_6.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.train_data_upload_button = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.train_data_upload_button.setFont(font)
        self.train_data_upload_button.setStyleSheet("border: 4px solid#a6aaaf;\n"
"border-radius: 5px;\n"
"padding: 1px 5px;\n"
"background-color: #a6aaaf;\n"
"")
        self.train_data_upload_button.setObjectName("train_data_upload_button")
        self.gridLayout_6.addWidget(self.train_data_upload_button, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.autoencoder_button = QtWidgets.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.autoencoder_button.setFont(font)
        self.autoencoder_button.setStyleSheet("border: 4px solid#a6aaaf;\n"
"border-radius: 5px;\n"
"padding: 1px 5px;\n"
"background-color: #a6aaaf;\n"
"")
        self.autoencoder_button.setObjectName("autoencoder_button")
        self.gridLayout_5.addWidget(self.autoencoder_button, 0, 1, 1, 1)
        self.yolo_button = QtWidgets.QPushButton(self.page_2)
        self.yolo_button.setMinimumSize(QtCore.QSize(0, 0))
        self.yolo_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yolo_button.setFont(font)
        self.yolo_button.setStyleSheet("border: 4px solid#a6aaaf;\n"
"border-radius: 5px;\n"
"padding: 1px 5px;\n"
"background-color: #a6aaaf;\n"
"")
        self.yolo_button.setObjectName("yolo_button")
        self.gridLayout_5.addWidget(self.yolo_button, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 2, 0, 1, 3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit.setStyleSheet("border: 2px solid#a6aaaf;\n"
"border-radius: 5px;\n"
"padding: 1px 5px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.upload_button = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.upload_button.setFont(font)
        self.upload_button.setStyleSheet("border: 4px solid#a6aaaf;\n"
"border-radius: 5px;\n"
"padding: 1px 5px;\n"
"background-color: #a6aaaf;\n"
"")
        self.upload_button.setObjectName("upload_button")
        self.horizontalLayout_2.addWidget(self.upload_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.anomaly_button = QtWidgets.QPushButton(self.page_4)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.anomaly_button.setFont(font)
        self.anomaly_button.setStyleSheet("border: 4px solid#a6aaaf;\n"
"border-radius: 5px;\n"
"padding: 1px 5px;\n"
"background-color: #a6aaaf;\n"
"")
        self.anomaly_button.setObjectName("anomaly_button")
        self.verticalLayout_3.addWidget(self.anomaly_button)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 432, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_5)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_7.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.content_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "체크메이트"))
        self.home_button.setText(_translate("MainWindow", "홈"))
        self.data_button.setText(_translate("MainWindow", "데이터"))
        self.learn_button.setText(_translate("MainWindow", "학습"))
        self.detect_button.setText(_translate("MainWindow", "검출"))
        self.helper_button.setText(_translate("MainWindow", "도움말"))
        self.label.setText(_translate("MainWindow", "체크메이트"))
        self.pushButton.setText(_translate("MainWindow", "데이터셋 추가"))
        self.pushButton_2.setText(_translate("MainWindow", "데이터셋 라벨링"))
        self.train_data_upload_button.setText(_translate("MainWindow", "불러오기"))
        self.autoencoder_button.setText(_translate("MainWindow", "AUTOENCODER 훈련"))
        self.yolo_button.setText(_translate("MainWindow", "YOLO 훈련"))
        self.upload_button.setText(_translate("MainWindow", "불러오기"))
        self.anomaly_button.setText(_translate("MainWindow", "검출"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
