# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtGui import QDesktopServices
import os, subprocess
import gui.resource_rc

from gui.file_manager import FileManager as FD

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("#menu_widget {\n"
        "    background-color: #112D4E;\n"
        "}\n"
        "#menu_widget QPushButton, QLabel{\n"
        "    height: 50px;\n"
        "    border: none;\n"
        "}\n"
        "#menu_widget QPushButton:hover{\n"
        "    background-color: #DBE2EF;\n"
        "}\n"
        "#menu_widget QLabel{\n"
        "    color: #F9F7F7;\n"
        "}\n"
        "#menu_widget QPushButton{\n"
        "    color:  #DBE2EF;\n"
        "   text-align: left;\n"
        "}\n"
        "#menu_widget QPushButton:hover{\n"
        "    color:  #112D4E;\n"
        "}\n"
        "#MainWindow{\n"
        "    background-color:#fff;\n"
        "}\n"
        # "#data_page QPushButton:hover{\n"
        # "    color: #fff;\n"
        # "}\n"
        "#train_page QPushButton:hover{\n"
        "    color: #fff;\n"
        "}\n"
        "#detect_page QPushButton:hover{\n"
        "    color: #fff;\n"
        "}\n")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.menu_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menu_widget.setObjectName("menu_widget")
        self.menu_widget.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.menu_widget)
        self.logo.setMinimumSize(QtCore.QSize(50, 50))
        self.logo.setMaximumSize(QtCore.QSize(50, 50))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icons/icons/icons8-출석-표-64.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        self.title = QtWidgets.QLabel(self.menu_widget)
        title_font = QtGui.QFont()
        title_font.setFamily("Noto Sans KR")
        title_font.setPointSize(15)
        title_font.setBold(True)
        self.title.setFont(title_font)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_button = QtWidgets.QPushButton(self.menu_widget)
        menu_font = QtGui.QFont()
        menu_font.setFamily("Noto Sans KR")
        menu_font.setPointSize(12)
        self.home_button.setFont(menu_font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-집-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon1)
        self.home_button.setIconSize(QtCore.QSize(25, 25))
        self.home_button.setCheckable(True)
        self.home_button.setAutoExclusive(True)
        self.home_button.setObjectName("home_button")
        self.verticalLayout.addWidget(self.home_button)
        self.data_button = QtWidgets.QPushButton(self.menu_widget)
        self.data_button.setFont(menu_font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-사진-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.data_button.setIcon(icon2)
        self.data_button.setIconSize(QtCore.QSize(25, 25))
        self.data_button.setCheckable(True)
        self.data_button.setAutoExclusive(True)
        self.data_button.setObjectName("data_button")
        self.verticalLayout.addWidget(self.data_button)
        self.learn_button = QtWidgets.QPushButton(self.menu_widget)
        self.learn_button.setFont(menu_font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-책-공개-시험-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.learn_button.setIcon(icon3)
        self.learn_button.setIconSize(QtCore.QSize(25, 25))
        self.learn_button.setCheckable(True)
        self.learn_button.setAutoExclusive(True)
        self.learn_button.setObjectName("learn_button")
        self.verticalLayout.addWidget(self.learn_button)
        self.detect_button = QtWidgets.QPushButton(self.menu_widget)
        self.detect_button.setFont(menu_font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-검사-48 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detect_button.setIcon(icon4)
        self.detect_button.setIconSize(QtCore.QSize(25, 25))
        self.detect_button.setCheckable(True)
        self.detect_button.setAutoExclusive(True)
        self.detect_button.setObjectName("detect_button")
        self.verticalLayout.addWidget(self.detect_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 248, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.helper_button = QtWidgets.QPushButton(self.menu_widget)
        self.helper_button.setFont(menu_font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-돋보기-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helper_button.setIcon(icon5)
        self.helper_button.setIconSize(QtCore.QSize(25, 25))
        self.helper_button.setCheckable(True)
        self.helper_button.setAutoExclusive(True)
        self.helper_button.setObjectName("helper_button")
        self.verticalLayout_2.addWidget(self.helper_button)
        self.gridLayout.addWidget(self.menu_widget, 0, 0, 1, 1)
        self.content_widget = QtWidgets.QWidget(self.centralwidget)
        self.content_widget.setObjectName("content_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.content_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.main_page)
        page_title_font = QtGui.QFont()
        page_title_font.setFamily("Noto Sans KR")
        page_title_font.setPointSize(16)
        page_title_font.setBold(True)
        self.label.setFont(page_title_font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.main_page)
        self.data_page = QtWidgets.QWidget()
        self.data_page.setObjectName("data_page")
        self.data_page.setStyleSheet("QPushButton {border: 4px solid #DBE2EF;\n"
        "border-radius: 5px;\n"
        "padding: 1px 5px;\n"
        "background-color: #DBE2EF;\n"
        "color: #112D4E;"
        "}"
        "QPushButton:hover{"
        "color: #fff}")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.data_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.data_add_button = QtWidgets.QPushButton(self.data_page)
        button_font = QtGui.QFont()
        button_font.setFamily("Noto Sans KR")
        button_font.setPointSize(9)
        button_font.setBold(True)
        self.data_add_button.setFont(button_font)
        # self.data_add_button.setStyleSheet("border: 4px solid #DBE2EF;\n"
        # "border-radius: 5px;\n"
        # "padding: 1px 5px;\n"
        # "background-color: #DBE2EF;\n"
        # "color: #112D4E;"
        # "")
        self.data_add_button.setObjectName("data_add_button")
        self.horizontalLayout_3.addWidget(self.data_add_button)
        self.data_label_button = QtWidgets.QPushButton(self.data_page)
        label_font = QtGui.QFont()
        label_font.setFamily("Noto Sans KR")
        label_font.setPointSize(9)
        # 이 부분은 충돌 오류 날 때마다 추가 부탁드립니다
        self.file_manager = FD()
        self.gridLayout_3.addWidget(self.file_manager, 2, 0, 1, 1)
        #
        self.data_label_button.setFont(button_font)
        # self.data_label_button.setStyleSheet("border: 4px solid #DBE2EF;\n"
        # "border-radius: 5px;\n"
        # "padding: 1px 5px;\n"
        # "background-color: #DBE2EF;\n"
        # "color: #112D4E;"
        # "")
        self.data_label_button.setObjectName("data_label_button")
        self.horizontalLayout_3.addWidget(self.data_label_button)
        self.dataset_create_button = QtWidgets.QPushButton(self.data_page)
        self.dataset_create_button.setFont(button_font)
        # self.dataset_create_button.setStyleSheet("border: 4px solid #DBE2EF;\n"
        # "border-radius: 5px;\n"
        # "padding: 1px 5px;\n"
        # "background-color: #DBE2EF;\n"
        # "color: #112D4E;"
        # "")
        self.dataset_create_button.setObjectName("dataset_create_button")
        self.horizontalLayout_3.addWidget(self.dataset_create_button)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 6, 0, 1, 1)
        self.data_label = QtWidgets.QLabel(self.data_page)
        self.data_label.setFont(title_font)
        self.data_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_label.setObjectName("data_label")
        self.gridLayout_3.addWidget(self.data_label, 0, 0, 1, 1)
        self.data_info_label = QtWidgets.QLabel(self.data_page)
        self.data_info_label.setFont(label_font)
        self.data_info_label.setObjectName("data_info_label")
        self.gridLayout_3.addWidget(self.data_info_label, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.data_page)
        self.train_page = QtWidgets.QWidget()
        self.train_page.setObjectName("train_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.train_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.train_page)
        self.label_2.setFont(page_title_font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.train_page)
        self.widget.setStyleSheet("#widget{\n"
                                  "    border: 2px solid#a6aaaf;\n"
                                  "    border-radius: 5px;\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(17, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.yolo_button = QtWidgets.QPushButton(self.widget)
        self.yolo_button.setMinimumSize(QtCore.QSize(0, 0))
        self.yolo_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.yolo_button.setFont(font)
        # self.yolo_button.setStyleSheet("border: 4px solid#a6aaaf;\n"
        #                                "border-radius: 5px;\n"
        #                                "padding: 1px 5px;\n"
        #                                "background-color: #a6aaaf;\n"
        #                                "")
        self.yolo_button.setObjectName("yolo_button")
        self.gridLayout_5.addWidget(self.yolo_button, 0, 0, 1, 1)
        self.efficientAD_button = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.efficientAD_button.setFont(font)
        # self.efficientAD_button.setStyleSheet("border: 4px solid#a6aaaf;\n"
        #                                       "border-radius: 5px;\n"
        #                                       "padding: 1px 5px;\n"
        #                                       "background-color: #a6aaaf;\n"
        #                                       "")
        self.efficientAD_button.setObjectName("efficientAD_button")
        self.gridLayout_5.addWidget(self.efficientAD_button, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(18, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.gridLayout_6.addWidget(self.widget, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 91, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.train_page)
        self.train_page.setStyleSheet("QPushButton {border: 4px solid #DBE2EF;\n"
        "border-radius: 5px;\n"
        "padding: 1px 5px;\n"
        "background-color: #DBE2EF;\n"
        "color: #112D4E;"
        "}"
        "QPushButton:hover{"
        "color: #fff}")
        self.detect_page = QtWidgets.QWidget()
        self.detect_page.setObjectName("detect_page")
        self.detect_page.setStyleSheet("QPushButton {border: 4px solid #DBE2EF;\n"
        "border-radius: 5px;\n"
        "padding: 1px 5px;\n"
        "background-color: #DBE2EF;\n"
        "color: #112D4E;"
        "}"
        "QPushButton:hover{"
        "color: #fff}")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.detect_page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_3 = QtWidgets.QLabel(self.detect_page)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setFont(title_font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_10.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.anomaly_detect_widget = QtWidgets.QWidget(self.detect_page)
        self.anomaly_detect_widget.setFont(label_font)
        self.anomaly_detect_widget.setStyleSheet("#anomaly_detect_widget{\n"
        "    border: 2px solid#a6aaaf;\n"
        "    border-radius: 5px;\n"
        "}")
        self.anomaly_detect_widget.setObjectName("anomaly_detect_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.anomaly_detect_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.anomaly_detect_widget)
        self.label_4.setFont(label_font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.anomaly_detect_widget)
        self.comboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setStyleSheet("""
            QComboBox {
                background-color: #fff;
                padding: 3px;
                border: 1px solid #a6aaaf;
                border-radius: 5px;
            }
            QComboBox:hover {
                background-color: #F9F9F9;
            }
            QComboBox:disabled {
                background-color: #F1F1F1;
                color: #A0A0A0;
            }
            QComboBox QAbstractItemView {
                background-color: #FFFFFF;
                border: 1px solid #112D4E;
                selection-background-color: #3F72AF;
                selection-color: #fff;
            }
            """)
        self.refresh_button = QtWidgets.QPushButton(self.anomaly_detect_widget)
        self.refresh_button.setIconSize(QtCore.QSize(40, 40))  # 버튼 크기 설정
        icon = QtGui.QIcon("gui/icons/refresh-icon-14.png")  # 이미지 파일 경로 설정
        self.refresh_button.setIcon(icon)  # 버튼에 이미지 설정
        self.refresh_button.setFixedSize(QtCore.QSize(40, 40))  # 버튼 크기 고정
        self.refresh_button.setStyleSheet("""
            QPushButton {
                background-color: transparent;
                border: none;
            }
            QPushButton:hover {
                background-color: #a6aaaf;
            }
        """)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.horizontalLayout_4.addWidget(self.refresh_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4, 0)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.detect_image_button = QtWidgets.QPushButton(self.anomaly_detect_widget)
        self.detect_image_button.setFont(button_font)
        # self.detect_image_button.setStyleSheet("border: 4px solid #DBE2EF;\n"
        # "border-radius: 5px;\n"
        # "padding: 1px 5px;\n"
        # "background-color: #DBE2EF;\n"
        # "color: #112D4E;"
        # "")
        self.detect_image_button.setObjectName("detect_image_button")
        self.horizontalLayout_2.addWidget(self.detect_image_button)
        self.detect_video_button = QtWidgets.QPushButton(self.anomaly_detect_widget)
        self.detect_video_button.setFont(button_font)
        # self.detect_video_button.setStyleSheet("border: 4px solid #DBE2EF;\n"
        # "border-radius: 5px;\n"
        # "padding: 1px 5px;\n"
        # "background-color: #DBE2EF;\n"
        # "color: #112D4E;"
        # "")
        self.detect_video_button.setObjectName("detect_video_button")
        self.horizontalLayout_2.addWidget(self.detect_video_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_9.addWidget(self.anomaly_detect_widget, 0, 0, 1, 1)
        self.anomaly_widget = QtWidgets.QWidget(self.detect_page)
        self.anomaly_widget.setStyleSheet("#anomaly_widget{\n"
        "    border: 2px solid#a6aaaf;\n"
        "    border-radius: 5px;\n"
        "}")
        self.anomaly_widget.setObjectName("anomaly_widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.anomaly_widget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.anomaly_widget)
        self.label_5.setFont(label_font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.anomaly_widget)
        self.pushButton.setFont(button_font)
        # self.pushButton.setStyleSheet("border: 4px solid #DBE2EF;\n"
        # "border-radius: 5px;\n"
        # "padding: 1px 5px;\n"
        # "background-color: #DBE2EF;\n"
        # "color: #112D4E;"
        # "")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.pushButton, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.anomaly_widget, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem3, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.detect_page)
        self.helper_page = QtWidgets.QWidget()
        self.helper_page.setObjectName("helper_page")
        self.vboxlay = QtWidgets.QVBoxLayout(self.helper_page)
        self.vboxlay.setObjectName("gridLayout_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.helper_page)
        font = QtGui.QFont()
        font.setFamily("Noto Sans KR")
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setFrameShape(QtWidgets.QTextBrowser.NoFrame)
        self.vboxlay.addWidget(self.textBrowser)
        self.pdf_link = QtWidgets.QLabel("<a href='open_pdf'>checkmate_tutorial.pdf</a>")
        self.pdf_link.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.pdf_link.linkActivated.connect(lambda: self.open_pdf_link())
        self.vboxlay.addWidget(self.pdf_link)
        self.stackedWidget.addWidget(self.helper_page)

        self.gridLayout_4.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.content_widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "체크메이트"))
        self.home_button.setText(_translate("MainWindow", "홈"))
        self.data_button.setText(_translate("MainWindow", "데이터"))
        self.learn_button.setText(_translate("MainWindow", "학습"))
        self.detect_button.setText(_translate("MainWindow", "검출"))
        self.helper_button.setText(_translate("MainWindow", "도움말"))
        self.label.setText(_translate("MainWindow", "Check Mate"))
        self.data_add_button.setText(_translate("MainWindow", "데이터 추가"))
        self.data_label_button.setText(_translate("MainWindow", "데이터 라벨링"))
        self.dataset_create_button.setText(_translate("MainWindow", "데이터셋 생성"))
        self.data_label.setText(_translate("MainWindow", "데이터"))
        self.data_info_label.setText(_translate("MainWindow", "모델 학습을 위한 데이터를 관리하는 메뉴입니다.\n"))
        self.label_2.setText(_translate("MainWindow", "학습"))
#        self.train_data_upload_button.setText(_translate("MainWindow", "불러오기"))
        self.yolo_button.setText(_translate("MainWindow", "YOLO 학습"))
        self.efficientAD_button.setText(_translate("MainWindow", "EfficientAD 학습"))
        self.label_3.setText(_translate("MainWindow", "불량 검출"))
        self.detect_image_button.setText(_translate("MainWindow", "이미지"))
        self.detect_video_button.setText(_translate("MainWindow", "영상"))
        self.label_4.setText(_translate("MainWindow", "YOLO 검출")) #추가
        self.label_5.setText(_translate("MainWindow", "EFFICIENT 검출")) #추가
        self.pushButton.setText(_translate("MainWindow", "이상 탐지")) #추가
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans KR\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Noto Sans KR\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans KR\';\">"
                                                          "안녕하세요. 제작자 Leemited입니다. 저희 프로그램을 사용해 주셔서 감사합니다.</span></p>"
                                                          "<p>해당 프로그램 Check Mate는 2024학년도 1학기 명지대학교 컴퓨터공학과 캡스톤디자인 수업에서 제작되었습니다.</p>"
                                                          "<p>데이터 관리, 모델 학습, 불량 검출 등의 메뉴로 구성되어있으며, 사용하는 모델로는 YOLOv5, EfficientAD가 있습니다.</p>"
                                                          "<p>자세한 설명은 아래에 있는 checkmate_tutorial.pdf를 참고해 주세요.</p>"
                                                          "<p>감사합니다.</p></body></html>"))

    def open_pdf_link(self):
        # 사용자의 시스템에서 PDF 뷰어 실행 파일 경로 가져오기
        pdf_viewer_path = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"  # 사용자 시스템에 맞게 수정
        if not os.path.exists(pdf_viewer_path):
            QtWidgets.QMessageBox.critical(None, "Error", "PDF Viewer not found!")
            return

        # 실제 PDF 파일 경로로 바꾸기
        pdf_path = "gui/tutorial/checkmate_tutorial.pdf"
        absolute_path = os.path.abspath(pdf_path)

        # 파일 존재 여부 확인
        if not os.path.exists(absolute_path):
            QtWidgets.QMessageBox.critical(None, "Error", f"File not found: {absolute_path}")
            return

        try:
            # PDF 파일 열기
            QDesktopServices.openUrl(QUrl.fromLocalFile(absolute_path))
            print(f"Opening PDF: {absolute_path}")  # 디버깅 메시지
        except Exception as e:
            QtWidgets.QMessageBox.critical(None, "Error", str(e))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
